---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma-stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dyedfox/my-argocd.git
    targetRevision: HEAD
    path: environments/stage
  destination:
    server: https://kubernetes.default.svc
    #namespace: uptime-kuma-stage  # Add explicit namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false  # Change to true to auto-create namespace
      - PrunePropagationPolicy=foreground
      - PruneLast=true